#!/usr/bin/env python3
"""
Plot Figure tov-profiles from precomputed EL chemical potential scan data.

6-panel figure:
  Top row: Phi(r), lapse N(r), V_eff(r)  [representative curves]
  Bottom: source, emergent core size vs mu/m0, Schwarzschild radius vs mu/m0

Loads data from tov_tk_chemical_el.npz (generated by tov_tk_chemical_el.py).
"""
import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt

d = np.load("tov_tk_chemical_el.npz", allow_pickle=True)
beta0 = float(d["beta0"])
m0 = float(d["m0"])
csq = float(d["csq"])
N = int(d["N"])
mu_values = d["mu_values"]

n_arr = np.arange(1, N + 1, dtype=np.float64)
g = 4.0 * np.pi * n_arr**2
t0 = 1.0


def get_n_eff(d, key):
    try:
        return int(d[f"{key}_n_eff"])
    except KeyError:
        return int(np.sum(d[f"{key}_V_defect"] > 1e-10))


def get_r_s_w(d, key, n_eff, N):
    try:
        return float(d[f"{key}_r_s_w"])
    except KeyError:
        w = d[f"{key}_lapse"]**2
        n_start = max(n_eff + 3, 5)
        n_end = min(N // 2, n_eff + 40)
        if n_start >= n_end:
            return 0.0
        idx = np.arange(n_start - 1, n_end)
        r_fit = n_arr[idx]
        basis = 1.0 / r_fit - 1.0 / N
        target = -(w[idx] - 1.0)
        return np.dot(basis, target) / np.dot(basis, basis)


# Filter to main branch only: monotonically increasing r_s, n_eff >= 3
all_mus = sorted(mu_values)
main_branch = []
prev_rs = 0
for mu in all_mus:
    key = f"mu{mu:.2f}"
    n_eff = get_n_eff(d, key)
    rs = get_r_s_w(d, key, n_eff, N)
    if n_eff >= 3 and rs > prev_rs * 0.9:  # monotonic r_s
        main_branch.append(mu)
        prev_rs = rs

# Representative subset for profile plots (top row): ~8-10 curves
mu_show_profiles = [mu for mu in main_branch
                    if mu/m0 in [round(x, 3) for x in
                    [0.017, 0.033, 0.067, 0.1, 0.167, 0.233, 0.333, 0.5, 0.6, 0.657]]]
# Fallback: pick evenly spaced from main branch
if len(mu_show_profiles) < 5:
    step = max(1, len(main_branch) // 10)
    mu_show_profiles = main_branch[::step]
    if main_branch[-1] not in mu_show_profiles:
        mu_show_profiles.append(main_branch[-1])

colors_prof = plt.cm.coolwarm(np.linspace(0, 1, len(mu_show_profiles)))

fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# Top row: profiles for representative mu values
for idx, mu in enumerate(mu_show_profiles):
    key = f"mu{mu:.2f}"
    Phi = d[f"{key}_Phi"]
    lapse = d[f"{key}_lapse"]
    V_defect = d[f"{key}_V_defect"]
    source = d[f"{key}_source"]
    n_eff = get_n_eff(d, key)

    c = colors_prof[idx]
    lab = rf'$\mu/m_0={mu/m0:.2f}$'
    zoom = min(max(n_eff + 15, 25), N)

    axes[0, 0].plot(n_arr[:zoom], Phi[:zoom], color=c, lw=1.5, label=lab)
    axes[0, 1].plot(n_arr[:zoom], lapse[:zoom], color=c, lw=1.5, label=lab)
    axes[0, 2].plot(n_arr[:zoom], V_defect[:zoom], color=c, lw=1.5, label=lab)
    axes[1, 0].plot(n_arr[:zoom], source[:zoom], color=c, lw=1.5, label=lab)

# Bottom row: summary panels over main branch
mus_main = np.array(main_branch)
mu_ratio = mus_main / m0
neffs = [get_n_eff(d, f"mu{mu:.2f}") for mu in main_branch]
r_s_vals = [get_r_s_w(d, f"mu{mu:.2f}", get_n_eff(d, f"mu{mu:.2f}"), N)
            for mu in main_branch]
minN_vals = [float(np.min(d[f"mu{mu:.2f}_lapse"])) for mu in main_branch]

axes[1, 1].plot(mu_ratio, neffs, 'ko-', lw=1.5, ms=3)
axes[1, 1].set_xlabel(r'$\mu/m_0$'); axes[1, 1].set_ylabel(r'$n_{\rm eff}$')
axes[1, 1].set_title(r'Emergent core size vs $\mu/m_0$')

axes[1, 2].plot(mu_ratio, r_s_vals, 'ro-', lw=1.5, ms=3)
axes[1, 2].set_xlabel(r'$\mu/m_0$')
axes[1, 2].set_ylabel(r'$r_s$')
axes[1, 2].set_title(r'Schwarzschild radius vs $\mu/m_0$ (from $w$-fit)')

# Mark fold point
mu_fold = main_branch[-1] / m0
for ax in [axes[1, 1], axes[1, 2]]:
    ax.axvline(mu_fold, color='k', ls=':', lw=1.2, alpha=0.6)
    ax.set_xlim(0, 1)

# Formatting
for ax in axes[0, :].flat:
    ax.grid(True, alpha=0.3); ax.legend(fontsize=7, loc='best')
    ax.set_xlabel('$n$ (shell)')
axes[1, 0].grid(True, alpha=0.3); axes[1, 0].legend(fontsize=7, loc='best')
axes[1, 0].set_xlabel('$n$ (shell)')
axes[1, 1].grid(True, alpha=0.3); axes[1, 2].grid(True, alpha=0.3)
axes[0, 0].set_title(r'$\Phi(r)$'); axes[0, 0].set_ylabel(r'$\Phi$')
axes[0, 1].set_title(r'Lapse $N(r)$'); axes[0, 1].set_ylabel(r'$N$')
axes[0, 2].set_title(r'$V_{\rm eff} = \max(0, m_0(1-N)-\mu)$')
axes[0, 2].set_ylabel(r'$V_{\rm eff}$')
axes[1, 0].set_title('Source'); axes[1, 0].set_ylabel('Source')
axes[1, 0].axhline(0, color='gray', ls='--', lw=0.5)

plt.suptitle(rf'TK star chemical potential scan: $\beta_0 t_0={beta0:.0f}$, '
             rf'$m_0={m0:.1f}$, $c_*^2={csq:.1f}$, $N_s={N}$',
             fontsize=14)
plt.tight_layout()
plt.savefig("fermion/numerical/figures/tov_tk_chemical.png", dpi=150)
plt.close()
print("Saved fermion/numerical/figures/tov_tk_chemical.png")
